---
title: "Carrera de la luz - Jan Polanco Velasco"
output: 
  flexdashboard::flex_dashboard:
    theme:
      bg: "#FFFFFF"
      fg: "#000000" 
      primary: "#2C3E50"
      base_font: !expr bslib::font_google("Prompt")
      code_font: !expr bslib::font_google("JetBrains Mono")
    orientation: rows
    social: menu
    source_code: embed
    navbar:
      - { title: "GitHub", href: "https://github.com/hamsomp3/act1_met_sim_est_tablero", align: right, icon: fa-github }
      - { title: "Jan Polanco", href: "https://www.linkedin.com/in/jan-polanco-velasco/", align: right, icon: fa-linkedin }
      - { title: "Carrera de la Luz 2022", href: "https://juanchocorrelon.com/", align: right, icon: ion-link}
---

```{r setup, include=FALSE, context = "server"}
library(flexdashboard)
library(ggplot2)
library(plotly)
library(paqueteMET)
library(knitr)




data("CarreraLuz22")

CarreraLuz22M = subset(CarreraLuz22, CarreraLuz22$sex=="Hombre")
CarreraLuz22F = subset(CarreraLuz22, CarreraLuz22$sex=="Mujer")

CarreraLuz22$origen <- gsub("Tuluá", "Tulua", CarreraLuz22$origen)
CarreraLuz22$origen <- ifelse(CarreraLuz22$origen == "Bogotá", "Bogota", CarreraLuz22$origen)
CarreraLuz22$origen <- ifelse(CarreraLuz22$origen == "Bogota D.c", "Bogota", CarreraLuz22$origen)
CarreraLuz22$origen <- ifelse(CarreraLuz22$origen == "Cali Valle", "Cali", CarreraLuz22$origen)
CarreraLuz22$origen <- ifelse(CarreraLuz22$origen == "Popayán", "Popayan", CarreraLuz22$origen)
CarreraLuz22$origen <- ifelse(CarreraLuz22$origen == "Florida Va", "Florida", CarreraLuz22$origen)
CarreraLuz22$origen <- ifelse(CarreraLuz22$origen == "Santander", "Santander De Quilichao", CarreraLuz22$origen)
CarreraLuz22$origen <- ifelse(CarreraLuz22$origen == "Tuluá", "Tulua", CarreraLuz22$origen)
CarreraLuz22$origen <- ifelse(CarreraLuz22$origen == "Jamundí", "Jamundi", CarreraLuz22$origen)
CarreraLuz22$nacionalidad <- ifelse(CarreraLuz22$nacionalidad ==0, "COL",CarreraLuz22$nacionalidad)
# tablas
EDA                 = summary(CarreraLuz22)
CATsex              = table(CarreraLuz22$sex)
CATorigen           = table(CarreraLuz22$origen)
CATcategoria        = table(CarreraLuz22$categoria)
CATnacionalidad     = table(CarreraLuz22$nacionalidad)





Theme2 = theme(
  axis.title.x = element_text(size = 8),
  axis.text.x = element_text(size = 8),
  axis.title.y = element_text(size = 8),
  # axis.text.y = element_blank(),
  axis.text = element_text( size = 8),
  legend.title = element_text(size = 8),
  legend.text = element_text(size = 8),  
  strip.text = element_text(size=8),
  title =element_text(size=8, face='bold')
  )# tamaño letra por grupos



# subconjuntossubsets-----------------------------------------------------------------------
genero    = CarreraLuz22$sex
edades    = CarreraLuz22$edad
origen    = CarreraLuz22$origen
categoria = CarreraLuz22$categoria
nacio     = CarreraLuz22$nacionalidad
```

## Row {.tabset .tabset-fade}

### Genero

```{r, fig.height=7}
library(plotly)
plotlyOutput("plotly")
plot_ly(x = genero, y = table(genero), type = "bar", name = "Género", 
        marker = list(color = c("blue", "pink")),
        text = paste("Hombres:",table(genero)[1],"<br>Mujeres:",table(genero)[2]),
        textposition = "outside") %>% 
  layout(title = "Frecuencia de Cada Género",
         xaxis = list(title = "Género"),
         yaxis = list(title = "Frecuencia"))
```

### Origenes

```{r}
library(plotly)
plotlyOutput("plotly")
plot_ly(x = origen, y = table(origen), type = "bar", name = "Orígen") %>%
  layout(title = "Frecuencia de Cada Orígen",
         xaxis = list(title = "Orígen"),
         yaxis = list(title = "Frecuencia"))
```

### Edad

```{r}
library(plotly)
plotlyOutput("plotly")
plot_ly(x = edades, y = table(edades), type = "histogram", name = "Edades")%>%
  layout(title = "Distribución de la edad de los corredores",
         xaxis = list(title = "Edad"),
         yaxis = list(title = "Frecuencia"),
         shapes = list(list(type = "line", x0 = mean(edades), x1 = mean(edades), y0 = 0, y1 = max(table(edades)),yref = "paper", line = list(color = "red", width = 2)),list(type = "line", x0 = mean(edades) - sd(edades), x1 = mean(edades) - sd(edades), y0 = 0, y1 = max(table(edades)), yref = "paper", line = list(color = "black", width = 2, dash = "dot")),list(type = "line", x0 = mean(edades) + sd(edades), x1 = mean(edades) + sd(edades), y0 = 0, y1 = max(table(edades)), yref = "paper", line = list(color = "black", width = 2, dash = "dot"))))
```

### Categoria

```{r}
library(plotly)
plotlyOutput("plotly")
plot_ly(labels = unique(categoria), values = table(categoria), type = "pie",
        textposition = "inside",
        marker = list(colors = c("blue", "orange", "green", "red", "purple")),
        text = paste(table(categoria))) %>% 
  layout(title = "Distribución de las categorías en la carrera",
         showlegend = TRUE)
```

### Nacionalidad

```{r}
library(plotly)
plotlyOutput("plotly")
plot_ly(labels = unique(CarreraLuz22$nacionalidad), values = table(CarreraLuz22$nacionalidad), type = "pie",
        textposition = "inside",
        text = paste(table(nacio))) %>%
  layout(title = "Distribución de los origenes de las personas",
         showlegend = TRUE)
```

## Row

### minimo {.value-box}

```{r}
valueBox(value =paste(round(min(CarreraLuz22$timerun/60),1), "min"), 
         caption = "Tiempo ganador", 
         icon = "fa-thumbs-up", 
         color = "#18BC9C")
```

### velocidad {.value-box}

```{r}
valueBox(value =paste(round(10070/min(CarreraLuz22$timerun),2),"m/s"), # ud1$cierre, 
         caption = "Máxima velocidad", 
         icon = "ion-ios-speedometer", 
         color = "#18BC9C")
```

### distancia {.value-box}

```{r}
valueBox(value = paste(10.07,"Km"), #ud1$min, 
         caption = "Distancia recorrida", 
         icon = "ion-android-pin", 
         color = "#18BC9C")
```

### volumen {.value-box}

```{r}
valueBox(value = paste(length(CarreraLuz22$timerun),"atletas"), 
         caption = "Número de participantes", 
         icon = "ion-android-contacts", 
         color = "#18BC9C")
```

### porcentaje {.value-box}

```{r}
valueBox(value = paste(round(length(CarreraLuz22F$timerun)/length(CarreraLuz22$timerun)*100,2),"%"), 
         caption = "Porcentaje mujeres", 
         icon = "ion-woman", 
         color = "#18BC9C")
```

### promedio {.value-box}

```{r}
valueBox(value = paste(round(mean(CarreraLuz22$timerun/60),2),"min"), 
         caption = "Tiempo promedio de carrera", 
         icon    = "ion-clock", 
         color   = "#18BC9C")
```

## 3rd Party Outputs {.tabset}

### General

```{r, width = "50%", center = TRUE}
knitr::kable(CarreraLuz22)
```

### EDA

```{r, width = "50%", center = TRUE }
knitr::kable(EDA)
```

### Sexo

```{r, width = "50%", center = TRUE, col.names = c("Sexo", "Frecuencia"), row.names = TRUE}
knitr::kable(CATsex)
```

### Origen

```{r, width = "50%", center = TRUE }
knitr::kable(CATorigen)
```

### Categoria

```{r, width = "50%", center = TRUE}
knitr::kable(CATcategoria)
```

### Nacionalidad

```{r, width = "50%", center = TRUE}
knitr::kable(CATnacionalidad)
```
